name: Build Website
on: [workflow_dispatch]
jobs:
  Build-Website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Cache Notion data
        uses: actions/cache@v2
        with:
          path: data
          key: data_v1
      - run: npm install
      - run: npm run build
      - name: Fetch content from Notion
        run: npm run fetch
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
