name: Build Website
on: [workflow_dispatch]
jobs:
  Build-Website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Cache Notion data
        uses: actions/cache@v2
        with:
          path: data
          key: data_v2
      - run: npm install
      - run: npm run build
      - name: Fetch content from Notion
        run: npm run fetch
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      - name: Build website
        run: npm run build-website
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
